# Generated by Django 3.1.3 on 2020-11-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('launch_date', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('live', 'Live'), ('pending', 'Pending'), ('archived', 'Archived')], db_index=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('order_field', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tilesapi.tile')),
            ],
        ),
    ]
